#!/usr/bin/env python3
# -- coding: utf-8 --
#
# Copyright (c) 2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from collections.abc import Callable
from pathlib import Path
from typing import ClassVar
from unittest import TestCase
from unittest.mock import patch

from runner.environment import MandatoryPropDescription, RunnerEnv
from runner.options.cli_options import get_args
from runner.options.config import Config
from runner.suites.runner_standard_flow import RunnerStandardFlow
from runner.test import test_utils


class EtsGeneratorCollectionsTest(TestCase):
    get_instance_id: ClassVar[Callable[[], str]] = lambda: test_utils.create_runner_test_id(__file__)
    config: Config
    data_folder: ClassVar[Callable[[], Path]] = lambda: test_utils.data_folder(__file__, test_data_folder="conf_coll")
    env_properties: ClassVar[list[MandatoryPropDescription]] = RunnerEnv.mandatory_props
    test_environ: ClassVar[dict[str, str]] = test_utils.test_environ(
        'TESTS_LOADING_TEST_ROOT', data_folder().as_posix())

    @patch.dict(os.environ, test_environ, clear=True)
    @patch('runner.options.local_env.LocalEnv.get_instance_id', get_instance_id)
    @patch('runner.utils.get_config_workflow_folder', data_folder)
    @patch('runner.utils.get_config_test_suite_folder', data_folder)
    @patch('runner.suites.test_lists.TestLists._cmake_build_properties', test_utils.test_cmake_build)
    @patch('sys.argv', ["runner.sh", "config-1", "test_suite_2_col"])
    def test_gen_for_collections(self) -> None:
        """
        test suite contains 2 collections (1 collection contains 1 test),
        tests will be generated by test suite generator
        expected result: 2 tests were generated
        """
        args = get_args(EtsGeneratorCollectionsTest.env_properties)
        self.config = Config(args)
        _ = RunnerStandardFlow(self.config)
        gen_folder = Path(os.environ["WORK_DIR"]) / 'gen'
        gen_tests = sorted(test.name for test in gen_folder.rglob("*") if test.is_file() and test.suffix == ".ets")

        expected_tests = ['simple_test.ets',
                          'simple_test_types.ets',
                          ]
        try:
            self.assertEqual(sorted(expected_tests), gen_tests)
        finally:
            test_utils.clear_after_test()

    @patch.dict(os.environ, test_environ, clear=True)
    @patch('runner.options.local_env.LocalEnv.get_instance_id', get_instance_id)
    @patch('runner.utils.get_config_workflow_folder', data_folder)
    @patch('runner.utils.get_config_test_suite_folder', data_folder)
    @patch('runner.suites.test_lists.TestLists._cmake_build_properties', test_utils.test_cmake_build)
    @patch('sys.argv', ["runner.sh", "config-1", "test_suite_3_col", "--filter", "*/inner/*"])
    def test_gen_for_collections_with_filter(self) -> None:
        """
        test suite contains 3 collections (5 test in total),
        tests will be generated by test suite generator applying filter.
        expected result: 1 test from test collection 03.types was generated
        """
        args = get_args(EtsGeneratorCollectionsTest.env_properties)
        self.config = Config(args)
        _ = RunnerStandardFlow(self.config)
        gen_folder = Path(os.environ["WORK_DIR"]) / 'gen'
        gen_tests = sorted(test.name for test in gen_folder.rglob("*") if test.is_file() and test.suffix == ".ets")

        expected_tests = ['simple_test_types.ets']
        try:
            self.assertEqual(sorted(expected_tests), gen_tests)
        finally:
            test_utils.clear_after_test()

    @patch.dict(os.environ, test_environ, clear=True)
    @patch('runner.options.local_env.LocalEnv.get_instance_id', get_instance_id)
    @patch('runner.utils.get_config_workflow_folder', data_folder)
    @patch('runner.utils.get_config_test_suite_folder', data_folder)
    @patch('runner.suites.test_lists.TestLists._cmake_build_properties', test_utils.test_cmake_build)
    @patch('sys.argv', ["runner.sh", "config-1", "test_suite_3_col", "--filter", "**/*test*"])
    def test_gen_for_collections_with_filter_2(self) -> None:
        """
        test suite contains 3 collections (5 test in total),
        tests will be generated by test suite generator applying filter.
        expected result: 5 test from all test collection
        """
        args = get_args(EtsGeneratorCollectionsTest.env_properties)
        self.config = Config(args)
        _ = RunnerStandardFlow(self.config)
        gen_folder = Path(os.environ["WORK_DIR"]) / 'gen'
        gen_tests = sorted(test.name for test in gen_folder.rglob("*") if test.is_file() and test.suffix == ".ets")

        expected_tests = ['simple_test_types.ets',
                          'simple_test.ets',
                          'template_test_0.ets',
                          'template_test_1.ets',
                          'template_test_2.ets']
        try:
            self.assertEqual(sorted(expected_tests), gen_tests)
        finally:
            test_utils.clear_after_test()

    @patch.dict(os.environ, test_environ, clear=True)
    @patch('runner.options.local_env.LocalEnv.get_instance_id', get_instance_id)
    @patch('runner.utils.get_config_workflow_folder', data_folder)
    @patch('runner.utils.get_config_test_suite_folder', data_folder)
    @patch('runner.suites.test_lists.TestLists._cmake_build_properties', test_utils.test_cmake_build)
    @patch('sys.argv', ["runner.sh", "config-1", "test_suite_3_col",
                        "--test-file", "03.types/inner/simple_test_types.ets"])
    def test_gen_for_collections_with_test_file(self) -> None:
        """
        test suite contains 3 collections (5 test in total), tst-fil is set explicitly.
        expected result: 1 test from test collection 03.types was generated
        """
        args = get_args(EtsGeneratorCollectionsTest.env_properties)
        self.config = Config(args)
        _ = RunnerStandardFlow(self.config)
        gen_folder = Path(os.environ["WORK_DIR"]) / 'gen'
        gen_tests = sorted(test.name for test in gen_folder.rglob("*") if test.is_file() and test.suffix == ".ets")

        expected_tests = ['simple_test_types.ets']
        try:
            self.assertEqual(sorted(expected_tests), gen_tests)
        finally:
            test_utils.clear_after_test()
